"""
================================================================================================
SISTEMA DE GESTION DE INVENTARIOS Y DISEÑO GRAFICO - TALLER DEL ROBLE COLOMBIANO
Proyecto web - Framework seleccionado: Django (Python)
================================================================================================

Justificacion de la eleccion del framework:

Se seleccionó el framework de Django porque el proyecto es de tipo web (NO standalone ni
movil), y Django implementa de forma nativa el patron de arquitectura
MVC (Modelo Vista Controlador), que es la arquitectura definida previamente
para este sistema.

Django incluye de forma integrada sistemas de autenticacion,
panel administrativo, ORM para el manejo de la base de datos, y un
sistema de enrutamiento (urls.py) que facilita separar claramente
las responsabilidades del sistema, tal como lo requiere el proyecto
academico que va a incluir multiples modulos (Material, Modelo, Cliente, Usuario,
Historial, Factura).

Es el framework mas adecuado frente a alternativas standalone (no aplica,
debido a que el proyecto es web) o moviles (no aplica, se definio arquitectura web con
posible version movil hibrida posterior), por lo cual Django cubre
exactamente el alcance tanto de esta evidencia como de este proyecto.
"""

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nm%ayak(@hh4tk)i5=c^6^6=@@ipu!yj*=z8w4zy)k$%-(o=g9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'materiales', # La aplicacion del proyecto registrada
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # debe ir antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middlewares.validation_middleware.ValidacionJSONMiddleware',
]

# Permite que React (puerto 5173) consuma esta API sin bloqueo del navegador
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

REST_FRAMEWORK = {
    #'DEFAULT_AUTHENTICATION_CLASSES': (
    #   'rest_framework_simplejwt.authentication.JWTAuthentication',
    #),
    # Comentado intencionalmente: nuestro sistema valida el token
    # manualmente con decoradores propios (ver api/middlewares/auth_decorators.py),
    # porque JWTAuthentication espera el modelo de usuarios nativos de Django.
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',  # backend que trae mysql-connector-python
        'NAME': 'mydb',
        'USER': 'root',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),   # RNF: mismo tiempo que el cierre de sesión del frontend
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # reutiliza la SECRET_KEY que Django ya genera
}